import Head from "next/head";
import HomePage from './Components/HomePage';

export default function Home() {
  return (
    <>
      <Head>
        <title>Piotr Syjud</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="color-scheme" content="light" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomePage />
    </>
  );
};
